#!/bin/bash

# Install Java 17
dnf install java-17-amazon-corretto -y

# Go to /opt for app setup
cd /opt

# Download latest Tomcat 11 (v11.0.12 instead of 11.0.10)
wget https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.12/bin/apache-tomcat-11.0.12.tar.gz

# Extract Tomcat
tar -zxvf apache-tomcat-11.0.12.tar.gz
cd apache-tomcat-11.0.12

# Give execute permission
chmod +x bin/*.sh

# Backup original tomcat-users.xml before editing
cp conf/tomcat-users.xml conf/tomcat-users.xml.bak

# Add admin user and roles safely
cat <<EOT > conf/tomcat-users.xml
<tomcat-users>
    <role rolename="manager-gui"/>
    <role rolename="manager-script"/>
    <user username="tomcat" password="root123" roles="manager-gui,manager-script"/>
</tomcat-users>
EOT

# Allow remote access to Manager and Host Manager (comment out restrictions)
sed -i 's/<Valve className="org.apache.catalina.valves.RemoteAddrValve".*/<!-- & -->/' webapps/manager/META-INF/context.xml
sed -i 's/<Valve className="org.apache.catalina.valves.RemoteAddrValve".*/<!-- & -->/' webapps/host-manager/META-INF/context.xml

# Start Tomcat
sh bin/startup.sh
